appName: ys-nodejs-development

mysql:
  host: 127.0.0.1
  port: 3306
  username: root
  password: root
  database: ys-nodejs
  dialect: mysql
  timezone: '+08:00'
  pool:
    max: 50
    min: 0
    acquire: 30000
    idle: 10000
  logging: false # 日志

Redis:
  host: 127.0.0.1
  port: 6379
  password:
